image: surnet/alpine-node-wkhtmltopdf:10.15.3-0.12.4-full

before_script:
  - apk add --no-cache bash curl git lftp wget unzip msttcorefonts-installer fontconfig libxrender-dev libintl libgcc ttf-cantarell ttf-inconsolata ttf-opensans ttf-linux-libertine && update-ms-fonts
  - wget https://use.fontawesome.com/releases/v5.9.0/fontawesome-free-5.9.0-desktop.zip -O fontAwesome.zip
  - unzip fontAwesome.zip
  - mkdir -p /usr/share/fonts/opentype
  - mv fontawesome-free-5.9.0-desktop/otfs /usr/share/fonts/opentype
  - fc-cache -fv
  - ./scripts/installers/installer_all.sh

variables:
  AWS_DEFAULT_REGION: eu-west-3 # The region of S3 bucket
  AWS_ACCESS_KEY_ID: ${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}

stages:
  - test
  - build
  - analyze
  - deploy

test:
  stage: test
  script:
    - ./scripts/test.sh

pages:
  stage: build
  script:
    - ./scripts/builder.sh
    - mkdir public
    - ./scripts/packer.sh
  artifacts:
    paths:
    - public
    - builds
  cache:
    paths:
      - builds
  only:
  - master

analyze:
  stage: analyze
  script:
    - ./scripts/analyzer.sh
  artifacts:
    paths:
    - public
    - builds
  cache:
    paths:
      - builds

dropbox:
  stage: deploy
  script:
    - ./scripts/uploaders/uploader_dropbox.sh

amason_s3:
  image: python:3.7.3-alpine3.10
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - pip install awscli # Install the SDK
  script:
    - ./scripts/uploaders/uploader_amazon_s3.sh