image: node:8-alpine

before_script:
  - apk add --no-cache bash curl git lftp
  - ./scripts/installers/installer_all.sh

variables:
  AWS_DEFAULT_REGION: eu-west-3 # The region of our S3 bucket
  AWS_ACCESS_KEY_ID: ${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ./scripts/test.sh

pages:
  stage: build
  script:
    - ./scripts/builder.sh
    - cp builds/html/index.html public/
  artifacts:
    paths:
    - public
    - builds
  cache:
    paths:
      - builds
  only:
  - master

dropbox:
  stage: deploy
  script:
    - ./scripts/uploaders/uploader_dropbox.sh

amason_s3:
  image: python:3.7.3-alpine3.10
  stage: deploy
  before_script:
    - pip install awscli # Install the SDK
  script:
    - ./scripts/uploaders/uploader_ftp.sh