image: registry.gitlab.com/patricioperpetua/resume/builder:latest

before_script:
  - ./scripts/installers/installer_all.sh

variables:
  CURRENT_BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - test
  - build
  - pages
  - deploy

test:
  stage: test
  script:
    - ./scripts/test.sh

build:
  stage: build
  script:
    - rm -rf builds/
    - ./scripts/builder.sh
  artifacts:
    name: "$CI_PROJECT_NAME-${CI_COMMIT_REF_NAME}-built"
    paths:
      - builds
  cache:
    paths:
      - builds

build:
  image: docker:19.03.12
  stage: build
  before_script:
    - echo "${REGISTRY_GITLAB_PASS}" | docker login registry.gitlab.com -u ${REGISTRY_GITLAB_USER} --password-stdin

  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH/builder docker
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/builder
  only:
    changes:
      - docker/**/*

pages:
  stage: pages
  script:
    - mkdir public
    - ./scripts/packer.sh
  artifacts:
    paths:
      - builds
      - public
  only:
  - master

analyze:
  stage: deploy
  script:
    - ./scripts/analyzer.sh
  artifacts:
    paths:
      - builds

dropbox:
  stage: deploy
  script:
    - ./scripts/uploaders/uploader_dropbox.sh
  only:
    variables:
      - $CI_PROJECT_PATH == "patricioperpetua/resume"

amazon_s3:
  image: python:3.7.3-alpine3.10
  variables:
    AWS_DEFAULT_REGION: eu-west-3 # The region of S3 bucket
    AWS_ACCESS_KEY_ID: ${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - pip install awscli # Install the SDK
  script:
    - ./scripts/uploaders/uploader_amazon_s3.sh
  only:
    variables:
      - $CI_PROJECT_PATH == "patricioperpetua/resume"