image: node:14-alpine

before_script:
  - apk add --no-cache bash curl git grep lftp wget wkhtmltopdf ca-certificates unzip msttcorefonts-installer fontconfig libgcc libstdc++ libx11 glib libxrender-dev libintl libgcc libcrypto1.1 libssl1.1  ttf-inconsolata ttf-linux-libertine ttf-dejavu ttf-droid ttf-freefont ttf-liberation ttf-ubuntu-font-family && update-ms-fonts
  - wget https://use.fontawesome.com/releases/v5.9.0/fontawesome-free-5.9.0-desktop.zip -O fontAwesome.zip
  - unzip fontAwesome.zip
  - mkdir -p /usr/share/fonts/opentype
  - mv fontawesome-free-5.9.0-desktop/otfs /usr/share/fonts/opentype
  - fc-cache -fv
  - ./scripts/installers/installer_all.sh

variables:
  CURRENT_BRANCH: ${CI_COMMIT_REF_NAME}

stages:
  - test
  - build
  - pages
  - deploy

test:
  stage: test
  script:
    - ./scripts/test.sh

build:
  stage: build
  script:
    - rm -rf builds/
    - ./scripts/builder.sh
  artifacts:
    paths:
      - builds
  cache:
    paths:
      - builds

pages:
  stage: pages
  script:
    - mkdir public
    - ./scripts/packer.sh
  artifacts:
    paths:
      - builds
      - public
  only:
  - master

analyze:
  stage: deploy
  script:
    - ./scripts/analyzer.sh
  artifacts:
    paths:
      - builds

dropbox:
  stage: deploy
  script:
    - ./scripts/uploaders/uploader_dropbox.sh
  only:
    variables:
      - $CI_PROJECT_PATH == "patricioperpetua/resume"

amazon_s3:
  image: python:3.7.3-alpine3.10
  variables:
    AWS_DEFAULT_REGION: eu-west-3 # The region of S3 bucket
    AWS_ACCESS_KEY_ID: ${AMAZON_S3_RESUME_WR_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AMAZON_S3_RESUME_WR_SECRET_ACCESS_KEY}
  stage: deploy
  before_script:
    - apk add --no-cache bash
    - pip install awscli # Install the SDK
  script:
    - ./scripts/uploaders/uploader_amazon_s3.sh
  only:
    variables:
      - $CI_PROJECT_PATH == "patricioperpetua/resume"